#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <file_to_use>"
		exit 1
fi

filename=$1
otherfile=$2

export CFILE="$filename"

export OCFILE="$otherfile"

output_file=${1%.*}
echo "$output_file"

if [ -n $OCFILE ]; then
	gcc -Wall -pedantic -Werror -Wextra -std=gnu89 "$CFILE" -o "$output_file"
else
  gcc -Wall -pedantic -Werror -Wextra -std=gnu89 "$OCFILE" "$CFILE" -o "$output_file"
fi
