#!/bin/bash

if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <file_to_use>"
		exit 1
fi

filename=$1

export CFILE="$filename"

gcc -Wall -pedantic -Werror -Wextra -std=gnu89 positive_or_negative.c "$CFILE" -o 0-main
